// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WoodSalesApi.Models;

#nullable disable

namespace WoodSalesApi.Migrations
{
    [DbContext(typeof(WoodSalesContext))]
    [Migration("20240120170325_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WoodSalesApi.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__client__3213E83F5D61896A");

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("WoodSalesApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(16, 2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("PK__product__3213E83F7B03D659");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("WoodSalesApi.Models.Sale", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateSale")
                        .HasColumnType("datetime")
                        .HasColumnName("date_sale");

                    b.Property<int>("IdClient")
                        .HasColumnType("int")
                        .HasColumnName("id_client");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(16, 2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("PK__sale__3213E83F76A51D31");

                    b.HasIndex("IdClient");

                    b.ToTable("sale", (string)null);
                });

            modelBuilder.Entity("WoodSalesApi.Models.SaleDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("IdProduct")
                        .HasColumnType("int")
                        .HasColumnName("id_product");

                    b.Property<long>("IdSale")
                        .HasColumnType("bigint")
                        .HasColumnName("id_sale");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(16, 2)")
                        .HasColumnName("total");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(16, 2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("PK__sale_det__3213E83F97D7E904");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdSale");

                    b.ToTable("sale_detail", (string)null);
                });

            modelBuilder.Entity("WoodSalesApi.Models.Sale", b =>
                {
                    b.HasOne("WoodSalesApi.Models.Client", "IdClientNavigation")
                        .WithMany("Sales")
                        .HasForeignKey("IdClient")
                        .IsRequired()
                        .HasConstraintName("FK__sale__id_client__4D94879B");

                    b.Navigation("IdClientNavigation");
                });

            modelBuilder.Entity("WoodSalesApi.Models.SaleDetail", b =>
                {
                    b.HasOne("WoodSalesApi.Models.Product", "IdProductNavigation")
                        .WithMany("SaleDetails")
                        .HasForeignKey("IdProduct")
                        .IsRequired()
                        .HasConstraintName("FK__sale_deta__id_pr__5070F446");

                    b.HasOne("WoodSalesApi.Models.Sale", "IdSaleNavigation")
                        .WithMany("SaleDetails")
                        .HasForeignKey("IdSale")
                        .IsRequired()
                        .HasConstraintName("FK__sale_deta__id_sa__5BE2A6F2");

                    b.Navigation("IdProductNavigation");

                    b.Navigation("IdSaleNavigation");
                });

            modelBuilder.Entity("WoodSalesApi.Models.Client", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("WoodSalesApi.Models.Product", b =>
                {
                    b.Navigation("SaleDetails");
                });

            modelBuilder.Entity("WoodSalesApi.Models.Sale", b =>
                {
                    b.Navigation("SaleDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
